### PR TITLE
Add type hints in module stub files

### LINKED ISSUE #4: Missing type hints/library stubs
When using mypy (or other type checkers), it cannot analyze the library correctly, because type hints are unavaliable.
Are you planning to implement type hints or stubs in the future?

Output of mypy:
```
error: Skipping analyzing "thefuzz": found module but no type hints or library stubs
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

### PR DESCRIPTION
**Pull request by Harry-Lees**
Add Type hints in stub files. This fixes #4. 
The hints were added in stub files to maintain backwards compatibility. If it's likely this PR might get merged, we can add a `py.typed` file and add MyPy to the Github actions to check the type hints in new PRs.

### CODE REVIEW

**Comment by hugovk** [comment]
Please could we have a new release with this? The last [release](https://pypi.org/project/thefuzz/0.19.0/) was 12 months ago. Thank you!

**Comment by erwaen** [comment]
> 

true

**Comment by hugovk** [comment]
@Harry-Lees It would be great to add the `py.typed` marker so Mypy can use this :)

**Comment by markedwards** [comment]
Please add the missing `py.typed` file.  It’s literally the easiest diff you can do.

**Comment by markedwards** [comment]
Added #57 since this closed thread is probably being ignored.

**Comment by Harry-Lees** [comment]
> Added #56 since this closed thread is probably being ignored.

The comments about the missing `py.typed` only came in after this PR was merged :), I'm sure you could open a new PR to add the missing file. As mentioned in the original PR comment it's probably also worth adding MyPy/ Pylance/ Another type checker as a CI step to ensure the type annotations stay correct when other changes are made.

**Pull request merged**
